export enum ProductCategory{
  Abrigos = "Abrigos",
  Cazadoras = "Cazadoras",
  Chalecos = "Chalecos",
  Trajes = "Trajes",
  Blazers = "Blazers",
  Camisas = "Camisas",
  Camisetas = "Camisetas",
  Polos = "Polos",
  Sudaderas = "Sudaderas",
  Chandal = "Chandal",
  Punto = "Punto",
  Pantalon = "Pantalon",
  Jeans = "Jeans",
  Bermuda = "Bermuda",
  Zapatos = "Zapatos",
  Bolsos = "Bolsos",
  Accesorios = "Accesorios"
}
